# ==========================================
# STAGE 1: Build
# ==========================================
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package metadata
COPY package*.json ./

# Install dependencies (requires package-lock.json to be committed)
RUN npm ci

# Copy the rest of the application
COPY . .

# Pass build arguments to environment variables so Vite/Astro can bake them into the client build
ARG PUBLIC_API_URL
ENV PUBLIC_API_URL=${PUBLIC_API_URL}

# Build the Astro SSR application
RUN npm run build

# ==========================================
# STAGE 2: Run
# ==========================================
FROM node:20-alpine AS runner

WORKDIR /app

# Copy built assets and node_modules from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

# Expose the port Astro uses by default
EXPOSE 4321

# Set host to 0.0.0.0 to allow external connections in Docker
ENV HOST=0.0.0.0
ENV PORT=4321

# Run the standalone Node.js server generated by Astro
CMD ["node", "./dist/server/entry.mjs"]
